version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - run: 
          command: |
              ruby \<<EOD
                puts "hello world"
              EOD
          name: hola
      - run:
          name: Check Python shell
          shell: python
          command: print("python")
      - run:
          name: Check Ruby shell
          shell: ruby
          command: puts 'ruby'
      - run:
          name: Check Node shell
          shell: node
          command: |
            console.log("node");
