version: 2.1
jobs:
  build:
    docker:
      - image: cimg/perl:stable
    steps:
      - checkout
      - run: 
          command: |
              print "aaa"
          name: hola
          shell: /usr/bin/env perl
