version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - run: 
          command: |
              #!/bin/ruby
              puts "aaa"
          name: hola
          shell: /bin/bash -euo pipefail
