version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - run: 
          command: |
              ruby \<<EOD
                puts "hello world"
              EOD
          name: hola
