version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run: 
          command: |
              print("aaa")
          name: hola
          shell: /usr/bin/env python
