version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - run: 
          command: |
              ruby \<<EOD
                puts "hello world"
              EOD
          name: hola
      - run:
          name: Check Ruby shell
          shell: /usr/bin/env ruby
          command: puts 'hi'
